class_name MusicBedLayer
extends Node

# T-416: per-zone MUSIC beds — a quiet, non-positional score layer under the T-111/T-305/T-409
# ambience. Music is a BED, not a 3D emitter: one AudioStreamPlayer per zone REGION on a dedicated
# "Music" bus, and only the region the listener is in is audible — the others sit at a deep
# attenuation and we CROSSFADE (gentle ~2.5s) between them as the player crosses a boundary, so the
# score never hard-cuts. Region choice is era-consistent by construction (Ashmoor regions resolve
# only inside the district, medieval regions only outside), and we ALSO fold in the shared
# AmbientFxLayer era gate as a belt-and-braces silence for any cross-era bed.
#
# Beds ship at ~-24 dB (well under the -17 dB meadow ambience design level) so the score colours the
# scene without competing with SFX; the settings "Music" slider trims the whole bus from there.
#
# The four pilot beds (T-416 slice 1) are generated by tools/musicgen (Stable Audio Open 1.0,
# owner-approved, run locally) and loop-processed by tools/musicgen/loopify.py; each ships with the
# T-415 loop-import discipline (edit/loop_mode=2 + a non-empty loop region + a gitignore exception).

const _AUD := "res://assets/audio/"
const MEADOW := _AUD + "music_meadow.wav"
const VILLAGE := _AUD + "music_village.wav"
const ASHMOOR_STREET := _AUD + "music_ashmoor_street.wav"
const SPEAKEASY := _AUD + "music_speakeasy.wav"

const BUS_NAME := "Music"
const MUSIC_BASE_DB := -24.0  # a quiet score bed, well under the -17 dB meadow ambience
const INACTIVE_ATTEN_DB := -60.0  # a region the listener is not in fades to ~inaudible
const CROSSFADE_DB_PER_SEC := 24.0  # ~2.5s to travel the full 60 dB gate — a gentle crossfade

# Region rects use the SAME [center_x, center_z, half_w, half_h] convention as WorldView's district
# rects (absf(p-c) < half). The starting-village core (T-305 zone cluster) and the speakeasy
# interior (T-409 ashmoor_speakeasy zone) each get their own bed; everything else in-era falls back
# to the open-field meadow bed / the Ashmoor street bed.
const VILLAGE_RECT := [7.0, 5.0, 33.0, 32.0]
const SPEAKEASY_RECT := [-423.75, 8.0, 8.0, 8.0]

const ERA_MEDIEVAL := 1
const ERA_ASHMOOR := 2

# name, era, stream. Order is documentation only — region_at() decides which is audible.
const REGIONS: Array = [
	{"name": "meadow", "era": ERA_MEDIEVAL, "stream": MEADOW},
	{"name": "village", "era": ERA_MEDIEVAL, "stream": VILLAGE},
	{"name": "ashmoor_street", "era": ERA_ASHMOOR, "stream": ASHMOOR_STREET},
	{"name": "speakeasy", "era": ERA_ASHMOOR, "stream": SPEAKEASY},
]

var player_count: int = 0  # headless-test accessor
var _players: Array = []  # [{node, name, era}]


static func _in_rect(x: float, z: float, r: Array) -> bool:
	return absf(x - float(r[0])) < float(r[2]) and absf(z - float(r[1])) < float(r[3])


# T-416: which music region a listener at (x,z) is in. Era-consistent by construction — the Ashmoor
# regions are only ever returned inside the district, the medieval regions only outside it — so the
# score never plays a cross-era bed. Pure + static, so the region map is headlessly unit-testable.
static func region_at(x: float, z: float) -> String:
	if WorldView.in_ashmoor_district(x, z):
		return "speakeasy" if _in_rect(x, z, SPEAKEASY_RECT) else "ashmoor_street"
	return "village" if _in_rect(x, z, VILLAGE_RECT) else "meadow"


# T-416: reuse the shared AmbientFxLayer era gate so a cross-era bed is silenced — a second guard
# behind the era-consistent region map (defense in depth, the same term the ambience beds use).
static func era_gate_atten(bed_era: int, hearer_era: int) -> float:
	return AmbientFxLayer.era_gate_atten(bed_era, hearer_era)


func _ensure_bus() -> void:
	# A dedicated "Music" bus routed to Master, so the settings slider trims the score independently
	# of ambience/SFX. Idempotent — created once, survives a re-_ready.
	if AudioServer.get_bus_index(BUS_NAME) != -1:
		return
	var idx := AudioServer.bus_count
	AudioServer.add_bus(idx)
	AudioServer.set_bus_name(idx, BUS_NAME)
	AudioServer.set_bus_send(idx, "Master")


func _ready() -> void:
	_ensure_bus()
	build_players()


# T-416: one looping, non-positional AudioStreamPlayer per region on the Music bus. Born silent
# (INACTIVE) so there is never a one-frame chord of all four beds at once; _process crossfades the
# active region up within ~2.5s. Idempotent-guarded so a double _ready never double-stacks.
func build_players() -> void:
	if not _players.is_empty():
		return
	for region: Dictionary in REGIONS:
		var stream := load(str(region["stream"])) as AudioStream
		if stream == null:
			continue  # fail-closed: a missing bed drops its player, never a silent-forever one
		if stream is AudioStreamWAV:
			(stream as AudioStreamWAV).loop_mode = AudioStreamWAV.LOOP_FORWARD
		var p := AudioStreamPlayer.new()
		p.name = "Music_" + str(region["name"])
		p.stream = stream
		p.bus = BUS_NAME
		p.volume_db = MUSIC_BASE_DB + INACTIVE_ATTEN_DB  # start inaudible; crossfade up if active
		p.autoplay = true
		add_child(p)
		p.play()
		_players.append({"node": p, "name": str(region["name"]), "era": int(region["era"])})
		player_count += 1


func _process(delta: float) -> void:
	if _players.is_empty():
		return
	var active := _active_region()
	var here := AmbientFxLayer.listener_era(self)
	var step := CROSSFADE_DB_PER_SEC * delta
	for e: Dictionary in _players:
		var node: AudioStreamPlayer = e["node"]
		var target := (
			MUSIC_BASE_DB if str(e["name"]) == active else MUSIC_BASE_DB + INACTIVE_ATTEN_DB
		)
		target += era_gate_atten(int(e["era"]), here)  # belt-and-braces cross-era silence
		node.volume_db = move_toward(node.volume_db, target, step)


# The region the audio listener is in; falls back to "meadow" headlessly. T-752: resolved through
# the shared AmbientFxLayer.listener_node — the AudioListener3D on the player BODY, not the camera
# ~8 m behind it. The village/speakeasy rects are small enough (33 m and 8 m half-widths) that a
# camera-measured region flipped the score's crossfade a full camera-length early or late, and a
# left-drag orbit at the boundary could swing the whole score by itself.
func _active_region() -> String:
	var lis := AmbientFxLayer.listener_node(self)
	if lis == null:
		return "meadow"
	var p := lis.global_position
	return region_at(p.x, p.z)
