#!/usr/bin/env bash
# Avalon ticket-status ledger — the single source of truth for "what's done".
#
# Reconciles each docs/tickets/**/T*.md declared status against git history on main,
# and writes a generated ledger to docs/tickets/STATUS.md.
#
# Status vocabulary (see docs/tickets/_TEMPLATE.md):
#   PROPOSED  written, no implementation commits yet
#   IN-PROGRESS  >=1 implementation commit, not complete
#   DONE  complete + tests pass, on a feature branch
#   MERGED  on main (terminal success)
#   DEFERRED / DESCOPED  terminal off-ramp (needs a reason)
#   TRACKED  reserved for TD-* tech-debt trackers
#
# Usage:
#   scripts/ticket-status.sh            regenerate docs/tickets/STATUS.md (default)
#   scripts/ticket-status.sh --update   same
#   scripts/ticket-status.sh --check    exit 1 if STATUS.md is stale OR drift detected
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

LEDGER="docs/tickets/STATUS.md"
MODE="update"
case "${1:-}" in
	--check) MODE="check" ;;
	--update | "") MODE="update" ;;
	*)
		echo "usage: $0 [--update|--check]" >&2
		exit 2
		;;
esac

# Normalized state keyword from a ticket file (handles "- State: X" and "**Status:** X").
extract_state() {
	local f="$1" raw kw
	raw=$(head -25 "$f" | grep -iE "\**(State|Status)\**[[:space:]]*:" | head -1 || true)
	kw=$(printf '%s' "$raw" \
		| grep -oiE "IN-PROGRESS|IN PROGRESS|PROPOSED|DONE|MERGED|CLOSED|DEFERRED|DESCOPED|TRACKED" \
		| head -1 | tr '[:lower:]' '[:upper:]' | tr ' ' '-' || true)
	[[ -z "$kw" ]] && kw="(none)"
	echo "$kw"
}

extract_title() {
	grep -m1 -E "^# (T|TD)-[0-9]+" "$1" 2>/dev/null \
		| sed -E 's/^# (T|TD)-[0-9]+:?[[:space:]]*//' || true
}

# Implementation commits on main mentioning a ticket id. Counts a commit ONLY when the ticket
# is the PRIMARY ticket in the subject — i.e. the first T-xxx after the hash. Excludes pure
# docs()/chore() commits (ticket authoring, notes) and Merge commits. This stops a commit that
# implements ticket A but merely *mentions* ticket B ("… file T-535", "… deferred T-573",
# "… fold in T-525") from being counted as implementation evidence for B (false-positive drift).
# Still catches both modern "feat(M1/T-027):" and early "T-004:" styles for the primary ticket.
impl_commit_lines() {
	git log main --oneline 2>/dev/null \
		| grep -viE "^[0-9a-f]+ (docs|chore)[:(]" \
		| grep -viE "^[0-9a-f]+ Merge " \
		| awk -v t="$1" '{
			line = $0; sub(/^[0-9a-f]+ /, "", line)
			if (match(line, /T-[0-9]+/) && substr(line, RSTART, RLENGTH) == t) print $0
		}' || true
}

# Date of the most recent IMPLEMENTATION commit for a ticket, or "—".
# Derived from impl_commit_lines (excludes docs/chore) so docs commits that merely
# mention a ticket id don't shift the date — keeps the ledger stable across pushes.
last_commit_date() {
	local h
	h=$(impl_commit_lines "$1" | head -1 | awk '{print $1}')
	if [[ -n "$h" ]]; then
		git log -1 --format=%cs "$h" 2>/dev/null || echo "—"
	else
		echo "—"
	fi
}

# A ticket is "drifted" if it claims no work yet but has implementation commits on main.
is_drift() {
	local state="$1" impl_count="$2"
	if [[ "$impl_count" -gt 0 && ( "$state" == "PROPOSED" || "$state" == "(none)" ) ]]; then
		return 0
	fi
	return 1
}

# Render the ledger body to stdout (deterministic — no volatile timestamps).
render_ledger() {
	cat <<'HDR'
# Ticket Status Ledger

<!-- GENERATED by scripts/ticket-status.sh — do not edit by hand. -->
<!-- Update with: ./scripts/ticket-status.sh --update -->

This is the single source of truth for "what's done". `ROADMAP.md` is the immutable plan;
this ledger is the live state reconciled from each ticket file against git history on `main`.

**Status vocabulary:** `PROPOSED` → `IN-PROGRESS` → `DONE` → `MERGED`; `DEFERRED`/`DESCOPED`
terminal; `TRACKED` for `TD-*`. A ⚠ flag means the declared status disagrees with git
(implementation commits exist but the ticket still reads PROPOSED) — run the reconciliation.

HDR

	# Milestone rollup
	echo "## Milestone rollup"
	echo
	echo "| Milestone | Status |"
	echo "|-----------|--------|"
	for ms in m0 m1 m2 m3 m4 m5 m6; do
		[[ -d "docs/tickets/$ms" ]] || continue
		local authored=0 closed=0
		while IFS= read -r f; do
			[[ -z "$f" ]] && continue
			authored=$((authored + 1))
			local st
			st=$(extract_state "$f")
			if [[ "$st" == "MERGED" || "$st" == "DONE" || "$st" == "CLOSED" \
				|| "$st" == "DEFERRED" || "$st" == "DESCOPED" || "$st" == "TRACKED" ]]; then
				closed=$((closed + 1))
			fi
		done < <(find "docs/tickets/$ms" -name "T*-*.md" | sort)
		# Planned = distinct T-### referenced in the milestone README (the ticket map),
		# else the authored count. Unauthored-but-planned tickets count as outstanding.
		local planned="$authored"
		if [[ -f "docs/tickets/$ms/README.md" ]]; then
			local refd
			refd=$(grep -oE 'T-[0-9]{3}' "docs/tickets/$ms/README.md" | sort -u | wc -l | tr -d ' ')
			[[ "$refd" -gt "$planned" ]] && planned="$refd"
		fi
		local mark="◷ in-progress"
		if [[ "$planned" -gt 0 && "$closed" -eq "$planned" ]]; then
			mark="✅ complete"
		elif [[ "$planned" -eq 0 ]]; then
			mark="— (no tickets authored)"
		fi
		printf "| %s | %s (%d/%d resolved) |\n" "$(echo "$ms" | tr '[:lower:]' '[:upper:]')" "$mark" "$closed" "$planned"
	done
	echo

	# Per-ticket table
	echo "## Tickets"
	echo
	echo "| Ticket | MS | Title | Declared | Impl commits | Last commit | Flag |"
	echo "|--------|----|-------|----------|--------------|-------------|------|"

	while IFS= read -r f; do
		[[ -z "$f" ]] && continue
		local id ms title state lines count date flag
		id=$(basename "$f" .md)
		ms=$(echo "$f" | sed -E 's#docs/tickets/(m[0-9])/.*#\1#' | tr '[:lower:]' '[:upper:]')
		title=$(extract_title "$f")
		state=$(extract_state "$f")
		lines=$(impl_commit_lines "$id")
		count=$(printf '%s' "$lines" | grep -c . || true)
		date=$(last_commit_date "$id")
		flag=""
		if is_drift "$state" "$count"; then flag="⚠ drift"; fi
		printf "| %s | %s | %s | %s | %s | %s | %s |\n" \
			"$id" "$ms" "$title" "$state" "$count" "$date" "$flag"
	done < <(find docs/tickets -name "T*-*.md" | sort -t/ -k4)
}

generated="$(render_ledger)"

if [[ "$MODE" == "check" ]]; then
	rc=0
	# Drift check
	if printf '%s' "$generated" | grep -q "⚠ drift"; then
		echo "[ticket-status] FAIL — status drift detected (PROPOSED ticket with impl commits):"
		printf '%s\n' "$generated" | grep "⚠ drift" | sed 's/^/  /'
		rc=1
	fi
	# Staleness check
	if [[ ! -f "$LEDGER" ]] || ! diff -q <(printf '%s\n' "$generated") "$LEDGER" >/dev/null 2>&1; then
		echo "[ticket-status] FAIL — $LEDGER is stale. Run: ./scripts/ticket-status.sh --update"
		rc=1
	fi
	[[ "$rc" -eq 0 ]] && echo "[ticket-status] pass"
	exit "$rc"
fi

printf '%s\n' "$generated" >"$LEDGER"
echo "[ticket-status] wrote $LEDGER"
